[project]
name = "ereader-easy-swedish-vertex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-aiplatform>=1.87.0",
    "google-cloud-bigquery>=3.31.0",
]
